/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrosRouteImport } from './routes/cadastros'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as LocaisDeColetaRouteImport } from './routes/locais-de-coleta'
import { Route as ParceriasRouteImport } from './routes/parcerias'
import { Route as UnidadesMoveisRouteImport } from './routes/unidades-moveis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosRoute = CadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisDeColetaRoute = LocaisDeColetaRouteImport.update({
  id: '/locais-de-coleta',
  path: '/locais-de-coleta',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceriasRoute = ParceriasRouteImport.update({
  id: '/parcerias',
  path: '/parcerias',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesMoveisRoute = UnidadesMoveisRouteImport.update({
  id: '/unidades-moveis',
  path: '/unidades-moveis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/campanhas': typeof CampanhasRoute
  '/estoque': typeof EstoqueRoute
  '/locais-de-coleta': typeof LocaisDeColetaRoute
  '/parcerias': typeof ParceriasRoute
  '/unidades-moveis': typeof UnidadesMoveisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/campanhas': typeof CampanhasRoute
  '/estoque': typeof EstoqueRoute
  '/locais-de-coleta': typeof LocaisDeColetaRoute
  '/parcerias': typeof ParceriasRoute
  '/unidades-moveis': typeof UnidadesMoveisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastros': typeof CadastrosRoute
  '/campanhas': typeof CampanhasRoute
  '/estoque': typeof EstoqueRoute
  '/locais-de-coleta': typeof LocaisDeColetaRoute
  '/parcerias': typeof ParceriasRoute
  '/unidades-moveis': typeof UnidadesMoveisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastros'
    | '/campanhas'
    | '/estoque'
    | '/locais-de-coleta'
    | '/parcerias'
    | '/unidades-moveis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastros'
    | '/campanhas'
    | '/estoque'
    | '/locais-de-coleta'
    | '/parcerias'
    | '/unidades-moveis'
  id:
    | '__root__'
    | '/'
    | '/cadastros'
    | '/campanhas'
    | '/estoque'
    | '/locais-de-coleta'
    | '/parcerias'
    | '/unidades-moveis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrosRoute: typeof CadastrosRoute
  CampanhasRoute: typeof CampanhasRoute
  EstoqueRoute: typeof EstoqueRoute
  LocaisDeColetaRoute: typeof LocaisDeColetaRoute
  ParceriasRoute: typeof ParceriasRoute
  UnidadesMoveisRoute: typeof UnidadesMoveisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros': {
      id: '/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof CadastrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais-de-coleta': {
      id: '/locais-de-coleta'
      path: '/locais-de-coleta'
      fullPath: '/locais-de-coleta'
      preLoaderRoute: typeof LocaisDeColetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcerias': {
      id: '/parcerias'
      path: '/parcerias'
      fullPath: '/parcerias'
      preLoaderRoute: typeof ParceriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades-moveis': {
      id: '/unidades-moveis'
      path: '/unidades-moveis'
      fullPath: '/unidades-moveis'
      preLoaderRoute: typeof UnidadesMoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrosRoute: CadastrosRoute,
  CampanhasRoute: CampanhasRoute,
  EstoqueRoute: EstoqueRoute,
  LocaisDeColetaRoute: LocaisDeColetaRoute,
  ParceriasRoute: ParceriasRoute,
  UnidadesMoveisRoute: UnidadesMoveisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
